### ISSUE TITLE
Would it be possible to crawl LBRY SDK DHT nodes?

### ISSUE THREAD

**Issue by kodxana** [dennis-tra/nebula-crawler#1]
I have question is it possible to crawl other things using DHT like for example LBRY SDK nodes (https://github.com/lbryio/lbry-sdk) port 4444 UDP and also for example torrent DHT?

**Comment by dennis-tra** [comment]
Hi @kodxana,

thanks for your interest in this crawler. `Nebula` does only work with networks that are built upon [libp2p](https://libp2p.io/), and that includes but is not limited to IPFS, Filecoin, Ethereum, and Polkadot. If LBRY is using libp2p, then it could very well be possible!

A first look at the repo that you linked suggests that they are using their homegrown implementation, though :/

**Comment by kodxana** [comment]
Hi there. @dennis-tra LBRY is adding support for announcing data over bittorrent tracker https://github.com/lbryio/tracker
Would it be possible to crawl data from it?
